export enum DoctorSpecialization{
    CARDIOLOGISTS = 'CARDIOLOGISTS',
    PSYCHIATRISTS = 'PSYCHIATRISTS',
    PEDIATRICIAN = 'PEDIATRICIAN',
    GYNECOLOGISTS = 'GYNECOLOGISTS',
    NEUROLOGISTS = 'NEUROLOGISTS',
    SURGEON = 'SURGEON',
    GENERAL_PHYSICIAN = 'GENERAL_PHYSICIAN',
    ORTHOPEDICS = 'ORTHOPEDICS',
    RADIOLOGISTS = 'RADIOLOGISTS'
}